### ISSUE TITLE
Failed to compile in Reshade 5.9.2

### ISSUE THREAD

**Issue by whitestar127** [Fubaxiusz/fubax-shaders#18]
Hi, when opening Reshade within F123 to use Perfect Perspective, I got the "failed to compile" for this particular shader. Sorry, can't remember the specific error text right now. I'll update this issue when I get home.

Windows 10, Ryzen 5600X, Nvidia 3080, surround triple screen.

**Comment by Fubaxiusz** [comment]
Can you check if the #PerfectPerspective.fx shader version is the latest 5.8.6 (right-click and see source)?

**Comment by whitestar127** [comment]
Hi again, sorry for delayed reply. I just downloaded it now and tested again. I'm getting these errors (see attached image).

![PerfectPerspective](https://github.com/Fubaxiusz/fubax-shaders/assets/59665373/e6b17191-2d83-4edd-beaa-ad98fc028a5f)

**Comment by Fubaxiusz** [comment]
@whitestar127 the fix is easy, just right-click and download all the files listed in the error message from the [Shaders](https://github.com/Fubaxiusz/fubax-shaders/tree/master/Shaders) folder and copy them where the PerfectPerspective.fx is:
[Shaders/ColorConversion.fxh](https://github.com/Fubaxiusz/fubax-shaders/raw/master/Shaders/ColorConversion.fxh)
[Shaders/LinearGammaWorkflow.fxh](https://github.com/Fubaxiusz/fubax-shaders/raw/master/Shaders/LinearGammaWorkflow.fxh)
[Shaders/BlueNoiseDither.fxh](https://github.com/Fubaxiusz/fubax-shaders/raw/master/Shaders/BlueNoiseDither.fxh)

These are some function used in multiple shaders. To reuse the code for many shaders I placed them in separate files which the shaders link to and need, to operate correctly.

**Comment by whitestar127** [comment]
Thanks, that worked. But now I'm getting these errors:

![PerfectPerspective2](https://github.com/Fubaxiusz/fubax-shaders/assets/59665373/7657ffa8-e400-4a87-af54-9f080e5309fc)

**Comment by Fubaxiusz** [comment]
🤔 can you try downloading the whole thing, and copying the same three files from there?
Here's the link: [The Whole Thing..](https://github.com/Fubaxiusz/fubax-shaders/archive/refs/heads/master.zip)

**Comment by whitestar127** [comment]
My apologies. Seems I hadn't read the instructions properly. Works now, thanks. You may close the issue. :)
And wow, this works brilliantly in the game! Thank you so much. 👍

**Comment by Fubaxiusz** [comment]
I'm glad to hear that 😊 Can you post screenshots of the game here? It always makes me happy when someone shares images with _PerfectPerspective.fx_. I will then close the issue.

**Comment by hotjay4gh** [comment]
it shows undeclared identifier ANISOTROPIC, what should i do?

**Comment by Fubaxiusz** [comment]
@hotjay4gh Please update ReShade, latest version is 6.3.1 it added support for anisotropic filtering, which makes the edges less pixelated.
